name: Sync Fork with Rebase

on:
  schedule:
    - cron: '0 0 * * *' # Esegue ogni giorno a mezzanotte
  workflow_dispatch: # Permette di eseguire manualmente il workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Necessario per il rebase

    - name: Set up Git user
      run: |
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/mrcanelas/tmdb-addon.git
        git fetch upstream
        git rebase upstream/main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      run: |
        git push --force-with-lease origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
